export const UPVOTE = 'UPVOTE'
export const DOWNVOTE = 'DOWNVOTE'
export const PROBLEMS = 'PROBLEMS'
export const IDEAS = 'IDEAS'
export const DELETE_PROBLEM = 'DELETE_PROBLEM'
export const NEW_PROBLEM = 'NEW_PROBLEM'
