export const PROBLEMS_READ = 'PROBLEMS_READ'
export const PROBLEM_CREATE = 'PROBLEM_CREATE'
export const IDEAS_READ = 'IDEAS_READ'

export const REQUEST_PROBLEMS_READ = 'REQUEST_PROBLEMS_READ'
export const RECEIVE_PROBLEMS_READ = 'RECEIVE_PROBLEMS_READ'
export const PROBLEMS_READ_ERROR = 'PROBLEMS_READ_ERROR'

export const REQUEST_PROBLEM_DELETE = 'REQUEST_PROBLEM_DELETE'
export const RECEIVE_PROBLEM_DELETE = 'RECEIVE_PROBLEM_DELETE'
export const PROBLEM_DELETE_ERROR = 'PROBLEM_DELETE_ERROR'

export const SHOW_PROBLEM_CREATE_FORM = 'SHOW_PROBLEM_CREATE_FORM'
export const REQUEST_PROBLEM_CREATE = 'REQUEST_PROBLEM_CREATE'
export const RECEIVE_PROBLEM_CREATE = 'RECEIVE_PROBLEM_CREATE'
export const PROBLEM_CREATE_ERROR = 'PROBLEM_CREATE_ERROR'

export const REQUEST_PROBLEM_UPDATE = 'REQUEST_PROBLEM_UPDATE'
export const RECEIVE_PROBLEM_UPDATE = 'RECEIVE_PROBLEM_UPDATE'
export const PROBLEM_UPDATE_ERROR = 'PROBLEM_UPDATE_ERROR'
